webtalk_init -webtalk_dir D:/2021-fall/Single Cycle Processor Designed in verilog/project/Single Cycle Processor/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_CPU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  7 15:58:05 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c96c9aa3-81f4-49c4-9722-0123f47c02d5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f5ad94dd237c43a38ac5661970999956" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1114147593 -regid "" -xml D:/2021-fall/Single Cycle Processor Designed in verilog/project/Single Cycle Processor/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_CPU_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/2021-fall/Single Cycle Processor Designed in verilog/project/Single Cycle Processor/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_CPU_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/2021-fall/Single Cycle Processor Designed in verilog/project/Single Cycle Processor/Single Cycle Processor.sim/sim_1/behav/xsim/xsim.dir/tb_CPU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
